from .two_samples_panels.normal_homogen_panel import NormalHomogenPanel
from .two_samples_panels.wilcoxon_panel import WilcoxonPanel
from .two_samples_panels.mann_whitney_U_panel import MannWhitneyUPanel
from .two_samples_panels.rank_mean_diff_panel import RankMeanDiffPanel
from .two_samples_panels.smirnov_kolmogorov_panel import SmirnovKolmogorovPanel
from .two_samples_panels.signs_criterion_panel import SignsCriterionPanel